name: PartialScreenShare
options:
  bundleIdPrefix: com.valentinsuess
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    DEVELOPMENT_TEAM: 5APTBTQ49T
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  PartialScreenShare:
    type: application
    platform: macOS
    sources:
      - path: PartialScreenShare
    info:
      path: PartialScreenShare/Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: PartialScreenShare
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSMainStoryboardFile: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.valentinsuess.PartialScreenShare
        GENERATE_INFOPLIST_FILE: NO
    scheme:
      testTargets:
        - PartialScreenShareTests

  PartialScreenShareTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: PartialScreenShareTests
    dependencies:
      - target: PartialScreenShare
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.valentinsuess.PartialScreenShareTests
        GENERATE_INFOPLIST_FILE: YES
